=== jlaute/JodaYellowBox/Resources/StateMachine/statemachine.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="statemachine" type="statemachineType"/>

    <xsd:complexType name="statemachineType">
        <xsd:sequence>
            <xsd:element name="class" type="xsd:string"/>
            <xsd:element name="graph" type="xsd:string"/>
            <xsd:element name="property_path" type="xsd:string"/>
            <xsd:element name="states" type="statesType"/>
            <xsd:element name="transitions" type="transitionsType"/>
            <xsd:element name="callbacks" type="callbacksType" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="statesType">
        <xsd:sequence>
            <xsd:element name="state" type="xsd:string" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="transitionsType">
        <xsd:sequence>
            <xsd:element name="transition" type="singleTransitionType" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="singleTransitionType">
        <xsd:sequence>
            <xsd:element name="from" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="to" type="xsd:string"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="callbacksType">
        <xsd:sequence>
            <xsd:element name="callback" type="singleCallbackType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="singleCallbackType">
        <xsd:sequence>
            <xsd:element name="from" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="to" type="xsd:string" minOccurs="0"/>
            <xsd:element name="on" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="do" type="doType"/>
            <xsd:element name="args" type="xsd:string" minOccurs="0" maxOccurs="2"/>
        </xsd:sequence>
        <xsd:attribute name="time" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="doType">
        <xsd:attribute name="class" type="xsd:string"/>
        <xsd:attribute name="fnc" type="xsd:string"/>
    </xsd:complexType>
</xsd:schema>

=== jlaute/JodaYellowBox/Resources/StateMachine/config.xml
<?xml version="1.0" encoding="utf-8"?>
<statemachine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="statemachine.xsd">

    <class>\JodaYellowBox\Models\Ticket</class>
    <graph>default</graph>
    <property_path>state</property_path>
    <states>
        <state>open</state>
        <state>approved</state>
        <state>rejected</state>
        <state>reopened</state>
    </states>
    <transitions>
        <transition name="approve">
            <from>open</from>
            <from>reopened</from>
            <to>approved</to>
        </transition>
        <transition name="reject">
            <from>open</from>
            <from>reopened</from>
            <to>rejected</to>
        </transition>
        <transition name="reopen">
            <from>rejected</from>
            <to>reopened</to>
        </transition>
    </transitions>
    <callbacks>
        <callback time="after" name="on-change">
            <on>approve</on>
            <on>reject</on>
            <on>reopen</on>
            <do class="@joda_yellow_box.sql_state_logger" fnc="log"/>
            <args>object</args>
            <args>event</args>
        </callback>
    </callbacks>
</statemachine>
